batch_size: 256
clip_gradient_norm: 0.8
clip_targets_to_zero:
- dis_efas5
commit_hash:
data_dir: ../../../data/CAMELS-ES
dataset: generic
device: cuda:0
dynamic_inputs:
- pr_emo1
- ta_emo1
- e0_emo1
epochs: 10
experiment_name: EFAS_test2
head: regression
hidden_size: 128
img_log_dir: 
  /content/drive/MyDrive/TFM/notebook/models/EFAS5/runs/EFAS_test2_1709_081849/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.01
  10: 0.005
  20: 0.001
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- KGE
model: cudalstm
num_workers: 2
number_of_basins: 163
optimizer: Adam
output_activation: linear
output_dropout: 0.5
package_version: 1.9.0
predict_last_n: 1
run_dir: /content/drive/MyDrive/TFM/notebook/models/EFAS5/runs/EFAS_test2_1709_081849
save_validation_results: true
save_weights_every: 1
seed: 123
seq_length: 365
static_attributes:
- elv_mean
- elv_min
- elv_max
- gradient_mean
- upArea_max
- forest
- irrigated
- other
- rice
- sealed
- water
- laiyrmax
- laiyrmean
- laiyrmin
- cropcoef_mean
- ksat1
- lambda1
- genua1
- soildepth1
- thetas1
- thetar1
- tstor_sum
- tstor_count
- area_sum
- area_count
- dom_yr
- ene_yr
- ind_yr
- liv_yr
target_variables:
- dis_efas5
test_basin_file: basins_test.txt
test_end_date: 30/09/2020
test_start_date: 01/10/2000
train_basin_file: basins_train.txt
train_dir: 
  /content/drive/MyDrive/TFM/notebook/models/EFAS5/runs/EFAS_test2_1709_081849/train_data
train_end_date: 30/09/2020
train_start_date: 01/10/2010
validate_every: 1
validate_n_random_basins: 100
validation_basin_file: basins_validation.txt
validation_end_date: 30/09/2010
validation_start_date: 01/10/2000
