periodo:
    inicio: 1991-10-01
    final: 2020-09-30
area:
    min: 100
    max:
seleccion:
    disponibilidad: 0.9
    n_años: 8
rutas:
    anuario_aforos: C:/Users/jcr693/Documents/anuario_aforos/
    EFAS: C:/Datasets/EFASv5/iberia/
    caravan: C:/Datasets/CAMELS-ESP/CAMELS-ESP3/

train_size: .6
val_size: .2
seed: 123


