# directorios de trabajo
rutas:
    anuario_aforos:
        orig: C:/Datasets/anuario_aforos
        repo: ../../data/anuario_aforos
    EFAS: 
        orig: C:/Datasets/EFASv5/iberia
        repo: ../../data/EFAS5
    EMO:
        orig: C:/Datasets/EMO1
        repo: ../../data/EMO1
    CAMELS: 
        orig: C:/Datasets/CAMELS-ES
        repo: ../../data/CAMELS-ES
        
# configuración de CAMELS-ES
CAMELS-ES:        
    # periodo de estudio
    periodo:
        inicio: 1991-10-01
        final: 2020-09-30
    # límites de área de cuenca
    area:
        min: 100
        max:
    # disponibilidad mínima de datos de caudal
    caudal:
        disponibilidad: 0.9
        n_años: 8

# configuración del modelo LSTM
modelo:
    train_size: .6
    val_size: .2
    seed: 123
crs: 4326 #'epsg:4326'


