batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
- streamflow
commit_hash:
data_dir: ../../data/CAMELS_ESP
dataset: generic
device: cuda:0
dynamic_inputs:
- total_precipitation_sum
- temperature_2m_min
- temperature_2m_max
- potential_evaporation_sum
- surface_net_solar_radiation_mean
- surface_pressure_mean
epochs: 30
experiment_name: Minho
head: regression
hidden_size: 128
img_log_dir: 
  /content/drive/MyDrive/GitHub/neuralhydrology/examples/07-Minho/runs/Minho_1508_144839/img_log
initial_forget_bias: 3
learning_rate:
  0: 0.01
  10: 0.005
  20: 0.001
log_interval: 5
log_n_figures: 1
log_tensorboard: true
loss: NSE
metrics:
- NSE
model: cudalstm
num_workers: 8
number_of_basins: 14
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.8.1
predict_last_n: 1
run_dir: 
  /content/drive/MyDrive/GitHub/neuralhydrology/examples/07-Minho/runs/Minho_1508_144839
save_validation_results: true
save_weights_every: 1
seed: 123
seq_length: 365
static_attributes:
- p_mean
- pet_mean
- aridity
- moisture_index
- seasonality
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
target_variables:
- streamflow
test_basin_file: test_basin_Minho.txt
test_end_date: 30/09/2013
test_start_date: 01/10/2011
train_basin_file: train_basin_Minho.txt
train_dir: 
  /content/drive/MyDrive/GitHub/neuralhydrology/examples/07-Minho/runs/Minho_1508_144839/train_data
train_end_date: 30/09/2020
train_start_date: 01/10/2015
validate_every: 1
validate_n_random_basins: 14
validation_basin_file: train_basin_Minho.txt
validation_end_date: 30/09/2015
validation_start_date: 01/10/2013
